main: com.davismariotti.chester.Chester
name: Chester
version: ${project.version}

permissions:
  chester.*:
    children:
      chester.trigger: true
      chester.log: true
  chester.trigger:
    default: true
  chester.log:
    default: true
